version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: prueba
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data\
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ktestnet

  ms-ktestfull:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/prueba
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SERVER_PORT: 8080
      SWAGGER_ENABLED: true
      USER_DEFAULT_ROLE: USER
    ports:
      - "8080:8080"
    networks:
      - ktestnet

volumes:
  postgres_data:

networks:
  ktestnet:
